### ISSUE TITLE
Incompatibility with scipy>=1.14.0

### ISSUE THREAD

**Issue by aaronkho** [freegs-plasma/freegs#115]
The `scipy` community has deprecated the backwards compatibility alias of the function name `scipy.integrate.cumtrapz` to its new name, `scipy.integrate.cumulative_trapezoid`. Due to this, this package cannot be integrated with workflows requiring more modern tooling requiring `scipy>=1.14.0`. Can you please update the names or create internal aliases if necessary.

The same applies to `scipy.integrate.trapz -> scipy.integrate.trapezoid`, in case it is relevant for this codebase. The new function names have been around since `scipy==1.6.0`, so I doubt changing them to will break any existing backwards compatibility.

**Comment by ZedThree** [comment]
Ah, this is actually fixed already, just not in the latest release. I'm just trying to sort some issues with building the docs and then I'll make a new release

**Comment by aaronkho** [comment]
Great, thanks for the quick reply! Looking forward to the new update. Feel free to close this issue once the release is made.

**Comment by ZedThree** [comment]
This is fixed in 0.8.2, now available on PyPI

**Comment by lormei** [comment]
There still seem to be references to functions depreciated with `scipy>=1.14.0` left, `scipy.interpolate.interp2d` is used in two places in `equilibrium.py`.

**Comment by ZedThree** [comment]
Thanks @lormei! This wasn't being hit in the tests. Resolved in #130
