### ISSUE TITLE
fortranformat

### ISSUE THREAD

**Issue by octmc** [freegs-plasma/freegs#119]
Installation issues on Debian 12 via: 
$ git clone https://github.com/freegs-plasma/freegs.git
$ cd freegs
$ python setup.py install --user

See log file in attachment. Any ideas?
[freegs_setup_log.txt](https://github.com/user-attachments/files/17965797/freegs_setup_log.txt)

**Comment by ZedThree** [comment]
Please can you try with:

```console
$ python -m venv venv
$ source venv/bin/activate
$ pip install .
```

`python setup.py install` is deprecated, and you should prefer `pip install` instead.

**Comment by octmc** [comment]
Thanks. This works:

$ python -m venv venv
$ source venv/bin/activate
$ pip install freegs
