### ISSUE TITLE
machine.controlAdjust does not properly update currents of multi-turn coils

### ISSUE THREAD

**Issue by gsrutherford** [freegs-plasma/freegs#74]
controlAdjust does not currently check if a coil has multiple turns. This leads to much too large currents being produced.

Suggestion: coil.current += dI.item() -> coil.current += dI.item()/coil.turns

https://github.com/freegs-plasma/freegs/blob/master/freegs/machine.py#L748

**Comment by bendudson** [comment]
Thanks @gsrutherford !

I thought this should be accounted for by the coil response functions, so long as the definition of `coil.current` is consistent between coil types. The `coil.current` variable should be the current in the circuit, and the total toroidal current is `coil.current * coil.nturns` (https://github.com/freegs-plasma/freegs/blob/master/freegs/coil.py#L69). The control system is adjusting circuit currents so `controlAdjust` is given changes in circuit current, not changes in toroidal current. It's possible that some coil type isn't consistent with this definition; which Coil type is this for?

The control system decides how much current should be added based on the response function returned by `controlPsi()`: https://github.com/freegs-plasma/freegs/blob/master/freegs/coil.py#L69
A change in circuit current `dI` passed to `controlAdjust` should produce a change in poloidal flux `dpsi`:
```
dpsi = coil.controlPsi(...) * dI
```
The `Coil` class includes nturns in `controlPsi`:
https://github.com/freegs-plasma/freegs/blob/master/freegs/coil.py#L156
while `MultiCoil` sums all the contributions from the separate strands:
https://github.com/freegs-plasma/freegs/blob/master/freegs/multi_coil.py#L137

Is `controlAdjust` here being called from one of the FreeGS control systems (https://github.com/freegs-plasma/freegs/blob/master/freegs/control.py) or somewhere else?

**Comment by gsrutherford** [comment]
Hi Ben - I found this problem when attempting to switch from Coils (with just 1 turn) to ShapedCoils (with n >1 turns). I should have tested if this occurred for Coils with multiple turns before making this issue. Sorry about that.

So from your response, it sounds like something in ShapedCoils is not behaving consistently.

**Comment by bendudson** [comment]
Thanks @gsrutherford yes I think that might be the problem: `ShapedCoil` doesn't seem to use the value of `turns` anywhere: It's taken as an argument to `__init__` but never used. 
`controlPsi` performs an integral over triangles here:
https://github.com/freegs-plasma/freegs/blob/master/freegs/shaped_coil.py#L94

I think to be consistent with other coils, the `result` arrays returned from `controlPsi`, `controlBr` and `controlBz` should all be multiplied by `self.turns`. I think that would make this coil consistent with `coil.current * coil.turns` being the total toroidal current.
What do you think?

Thanks for finding & reporting this!

**Comment by gsrutherford** [comment]
@bendudson looks like that would bring ShapedCoil in line with how Coil uses its turns variable. Sounds good to me!

Edit 12/14/22: I modified my local files as detailed above, and now I get total coil currents very similar to single turn coil currents. Seems to have solved the issue.
