### ISSUE TITLE
Pypi has no 0.7.0 release

### ISSUE THREAD

**Issue by hattom** [freegs-plasma/freegs#93]
Pypi thinks the latest version is 0.6.1 [1]

I wonder if this is because of the change of repository (it also links to [2] under "Homepage"), or maybe something else (e.g. tags vs releases)?

[1] https://pypi.org/project/FreeGS/#history
[2] https://github.com/bendudson/freegs

**Comment by ZedThree** [comment]
Hmm, not quite sure what's happened there. Could be because 0.7.0 is a tag not a release, so the automated publishing workflow didn't trigger. Although I'm not sure if that workflow was added before or after that tag.

@bendudson I can upload 0.7.0 manually if you like? It might also be time for a new release anyway?

**Comment by bendudson** [comment]
Thanks @ZedThree! yes please; you're right it's probably time for a new release.

**Comment by ZedThree** [comment]
Ok, I've uploaded 0.7.0 manually. I had to make some manual changes so that `twine` was happy:

```diff
modified   README.md
@@ -137,7 +137,7 @@ Longer-term the intent is to move FreeGS development back to a public repo and t
 develop bespoke TE scripts in the eqtools python module.
 
 Public Versions
---------
+---------------
 
 0.6.1  11th February 2021
   - Fixes for HDF5 reading and writing
deleted    dist/FreeGS-0.7.0-py3.7.egg (binary)
modified   setup.py
@@ -18,6 +18,7 @@ setup(
     description="Free boundary Grad-Shafranov solver for tokamak plasma equilibria",
 
     long_description=read("README.md"),
+    long_description_content_type="text/markdown",
     
     install_requires=['numpy>=1.8',
                       'scipy>=0.14',
```

This would be an issue if someone checked the md5sum of the source from PyPI compared to the source at the tag `v0.7.0`, but otherwise shouldn't be a problem.

**Comment by ZedThree** [comment]
@bendudson Are you ok if I go ahead and release v0.8.0?

**Comment by bendudson** [comment]
Sounds good, thanks @ZedThree !
